name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Droneroo
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze -project Droneroo.xcodeproj -scheme "Droneroo" -destination "generic/platform=macOS" -destination "generic/platform=iOS" | xcpretty && exit ${PIPESTATUS[0]}
